[package]
name = "ssd1322"
version = "0.1.0"
authors = ["Kyle Schaffrick <kyle@raidi.us>"]

[dependencies]
embedded-hal = "0.2"
nb = "0.1"

[dependencies.itertools]
version = "0.7"
default-features = false

[features]
default = ["std"]
std = []
